version: '3.7'

services:
  lemonbot:
    build:
      context: .
      dockerfile: ./docker/tyrant.Dockerfile
    container_name: tyrant
    restart: unless-stopped
    tty: true
    volumes:
      - ./tyrant:/tyrant/tyrant:ro
      - ./logs:/tyrant/logs
      - ./images:/tyrant/images:ro
      - ./fonts:/tyrant/fonts:ro
    env_file:
      - .env
